#!/usr/bin/env bash

#
# Abort with <msg>
#

abort() {
  echo
  echo "  $@" 1>&2
  echo
  exit 1
}

if [ \( -z "$1" \) -o \( -z "$2" \) -o \( -z "$3" \) ]; then
	abort no enough parameter
fi

repo=$1
path=/tmp/$2
cfgpath="${3:-config/ops.env}"
ref="${4:-develop}"
oldcwd=$PWD

if [ -d "$path" ]; then
	rm -rf "$path"
fi

mkdir -p "$path"

echo cloning $repo @ $ref to $path
git clone $repo $path
cd $path

git checkout $ref

npm ci

if [ -f "$cfgpath" ]; then
	cp "$cfgpath" .test.env
fi

npm run lint -- --quiet --format=json --output-file /tmp/$2.lint 2> /tmp/$2.lint.err
npm run test -- --json --ci --forceExit --detectOpenHandles --outputFile=/tmp/$2.test 2> /tmp/$2.test.err

cd $oldcwd
rm -rf $path
