#!/usr/bin/env bash

#
# Abort with <msg>
#

abort() {
  echo
  echo "  $@" 1>&2
  echo
  exit 1
}

if [ \( -z "$1" \) -o \( -z "$2" \) -o \( -z "$3" \) ]; then
	abort no enough parameter
fi

repo=$1
path=/tmp/$2
cfgpath="${3:-config/ops.env}"
ref="${4:-develop}"
oldcwd=$PWD

if [ -d "$path" ]; then
	rm -rf "$path"
fi

mkdir -p "$path"

echo cloning $repo @ $ref to $path
git clone $repo $path
cd $path

git checkout $ref

npm ci

if [ -f "$cfgpath" ]; then
	cp "$cfgpath" .test.env
fi

npm run lint:ci /tmp/$2.lint
npm run test:ci > /tmp/$2.result

cd $oldcwd
rm -rf $path
